------------------------------------------------------------
-- ▶ 드롭 / DROP ◀
------------------------------------------------------------
DROP TABLE "C##EYELEVEL"."ANSWER";
DROP TABLE "C##EYELEVEL"."BUSINESS_LOG";
DROP TABLE "C##EYELEVEL"."CALENDAR";
DROP TABLE "C##EYELEVEL"."CATEGORY";
DROP TABLE "C##EYELEVEL"."COUNSELING";
DROP TABLE "C##EYELEVEL"."COUNSELING_CATEGORY";
DROP TABLE "C##EYELEVEL"."PAPER_INFOMATION";
DROP TABLE "C##EYELEVEL"."QUESTION";
DROP TABLE "C##EYELEVEL"."REPLY";
DROP TABLE "C##EYELEVEL"."STUDENT_FAMILY";
DROP TABLE "C##EYELEVEL"."TEACHER_AREA";
DROP TABLE "C##EYELEVEL"."TEACHING_AREA";
DROP TABLE "C##EYELEVEL"."ADMIN";
DROP TABLE "C##EYELEVEL"."AUTHORITY";
DROP TABLE "C##EYELEVEL"."MEMBER_ROLE";
DROP TABLE "C##EYELEVEL"."BOARD";
--DROP TABLE "C##EYELEVEL"."FILE";
DROP TABLE "C##EYELEVEL"."FILES";
DROP TABLE "C##EYELEVEL"."STUDENT_PROFILE";
DROP TABLE "C##EYELEVEL"."TEACHER_PROFILE";
-- ▶ 시퀀스 드롭 / DROP ◀
DROP SEQUENCE SEQ_CALENDAR_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_CATEGORY_CODE;
DROP SEQUENCE SEQ_COUNSELING_NO;
DROP SEQUENCE SEQ_PAPER_NO;
DROP SEQUENCE SEQ_REPLY_NO;
DROP SEQUENCE SEQ_STUDENT_NO;
DROP SEQUENCE SEQ_TEACHER_NO;
DROP SEQUENCE SEQ_AREA_NO;
DROP SEQUENCE SEQ_QUESTION_NO;
DROP SEQUENCE SEQ_AREA_COLUNM_NO;
DROP SEQUENCE SEQ_ANSWER_NO;
DROP SEQUENCE SEQ_FILES_NO;
------------------------------------------------------------
-- ▶ 시퀀스 / SEQUENCE ◀
------------------------------------------------------------

CREATE SEQUENCE SEQ_CALENDAR_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_CODE
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_COUNSELING_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_PAPER_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_REPLY_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_STUDENT_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_TEACHER_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_AREA_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_QUESTION_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_ANSWER_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_AREA_COLUNM_NO
START WITH 100
NOCACHE;
CREATE SEQUENCE SEQ_FILES_NO
START WITH 100
NOCACHE;

-----------------------------------------------------------
-- ▶ 테이블 생성 / CREATE ◀
------------------------------------------------------------
CREATE TABLE "BUSINESS_LOG" (
	"BUSINESS_DATE"	DATE		NOT NULL,
	"STUDENT_NO"	NUMBER		NOT NULL,
	"BUSINESS_MEMO"	VARCHAR2(4000)		NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL,
	"PAPER_NO"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "PAPER_INFOMATION" (
	"PAPER_NO"	VARCHAR2(20)		NOT NULL,
	"PAPER_NAME"	VARCHAR2(200)		NOT NULL,
	"PAPER_DIFF"	VARCHAR2(10)		NOT NULL,
	"PAPER_SUB"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "TEACHER_PROFILE" (
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL,
	"TEACHER_NAME"	VARCHAR2(10)		NOT NULL,
	"TEACHER_PICTURE"	VARCHAR2(500)		NULL,
	"TEACHER_ADDRESS"	VARCHAR2(160)		NOT NULL,
	"TEACHER_PHONE"	VARCHAR2(20)		NOT NULL,
	"TEACHER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"TEACHER_ID"	VARCHAR2(20)		NOT NULL,
	"TEACHER_PW"	VARCHAR2(100)		NOT NULL,
	"TEACHER_ENT"	CHARACTER		NOT NULL,
	"TEACHER_LEVEL"	VARCHAR2(20)		NULL,
	"TEACHER_PR"	VARCHAR2(1000)		NULL
);

CREATE TABLE "TEACHING_AREA" (
	"AREA_NO"	NUMBER		NOT NULL,
	"AREA_SI"	VARCHAR2(20)		NOT NULL,
	"AREA_GU"	VARCHAR2(20)		NULL,
	"AREA_DONG"	VARCHAR2(20)		NULL
);

CREATE TABLE "STUDENT_PROFILE" (
	"STUDENT_NO"	NUMBER		NOT NULL,
	"STUDENT_NAME"	VARCHAR2(10)		NOT NULL,
	"STUDENT_ID"	VARCHAR2(20)		NOT NULL,
	"STUDENT_PW"	VARCHAR2(100)		NOT NULL,
	"STUDENT_GENDER"	VARCHAR2(8)		NOT NULL,
	"STUDENT_PHONE"	VARCHAR2(20)		NOT NULL,
	"STUDENT_ADDRESS"	VARCHAR2(160)		NOT NULL,
	"STUDENT_REGIST"	DATE		NOT NULL,
	"STUDENT_MEMO"	VARCHAR2(200)		NULL,
	"STUDENT_STATUS"	CHARACTER		NOT NULL,
	"AREA_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CATEGORY" (
	"CATEGORY_CODE"	VARCHAR2(20)		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_DATE"	DATE		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"BOARD_NAME"	VARCHAR2(100)		NOT NULL,
	"CATEGORY_CODE"	VARCHAR2(20)		NOT NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"REPLY_DATE"	DATE		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "QUESTION" (
	"QUESTION_NO"	NUMBER		NOT NULL,
	"QUESTION_DATE"	DATE		NOT NULL,
	"QUESTION_NAME"VARCHAR2(100)		NOT NULL,
	"QUESTION_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"QUESTION_FILE"	VARCHAR2(500)		NULL,
	"QUESTION_COM"	CHARACTER		NULL,
	"STUDENT_NO"	NUMBER		NOT NULL
);

CREATE TABLE "ANSWER" (
	"ANSWER_NO"	NUMBER		NOT NULL,
	"QUESTION_NO"	NUMBER		NOT NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL,
	"ANSWER_DATE"	DATE		NOT NULL,
	"ANSWER_CONTENT"	VARCHAR2(1000)		NOT NULL
);

CREATE TABLE "STUDENT_FAMILY" (
	"FAMILY_NO"	NUMBER		NOT NULL,
	"FAMILY_REL"	VARCHAR2(20)		NOT NULL,
	"FAMILY_PHONE"	VARCHAR2(20)		NOT NULL,
	"FAMILY_AGE"	NUMBER		NOT NULL,
	"STUDENT_NO"	NUMBER		NOT NULL
);

CREATE TABLE "COUNSELING_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(20)	NOT NULL
);

CREATE TABLE "COUNSELING" (
	"COUNSELING_NO"	NUMBER		NOT NULL,
	"COUNSELING_PHONE"	VARCHAR2(20)		NOT NULL,
	"COUNSELING_ST"	VARCHAR2(1000)		NULL,
	"COUNSELING_COM"	CHARACTER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TEACHER_AREA" (
	"COLUNM_NO"	NUMBER		NOT NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL,
	"AREA_NO"	NUMBER		NOT NULL
);

CREATE TABLE "AUTHORITY" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"AUTHORITY_NAME"	VARCHAR2(255)		NULL
);

CREATE TABLE "MEMBER_ROLE" (
	"MEMBERAUTHORITY_NO"	NUMBER		NOT NULL,
	"TEACHER_NO"	VARCHAR2(20)		NOT NULL,
	"STUDENT_NO"	VARCHAR2(20)		NOT NULL,
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"ADMIN_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "ADMIN" (
	"ADMIN_CODE"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR2(255)		NOT NULL,
	"ADMIN_PW"	VARCHAR2(255)		NOT NULL,
	"ADMIN_NAME"	VARCHAR2(255)		NOT NULL
);
CREATE TABLE "C##EYELEVEL"."FILES" 
   (   "FILE_NO" NUMBER, 
   "TEACHER_NO" VARCHAR2(20 BYTE), 
   "FILE_TYPE" VARCHAR2(20 BYTE), 
   "FILE_ORIGIN_NAME" VARCHAR2(255 BYTE), 
   "FILE_SAVE_NAME" VARCHAR2(255 BYTE), 
   "FILE_PATH" VARCHAR2(255 BYTE), 
   "THUMBNAIL_PATH" VARCHAR2(255 BYTE)
   );

CREATE TABLE "C##EYELEVEL"."CALENDAR" 
   (	"ID" NUMBER, 
	"GROUPID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"START1" DATE, 
	"END1" DATE, 
	"ALLDAY" NUMBER(1,0), 
	"TEXTCOLOR" VARCHAR2(50 BYTE), 
	"BACKGROUNDCOLOR" VARCHAR2(50 BYTE), 
	"BORDERCOLOR" VARCHAR2(50 BYTE),
	"TEACHER_NAME" VARCHAR2(50 BYTE)
   );
ALTER TABLE "COUNSELING_CATEGORY" ADD CONSTRAINT "PK_COUNSELING_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "BUSINESS_LOG" ADD CONSTRAINT "PK_BUSINESS_LOG" PRIMARY KEY (
	"BUSINESS_DATE",
	"STUDENT_NO"
);

ALTER TABLE "PAPER_INFOMATION" ADD CONSTRAINT "PK_PAPER_INFOMATION" PRIMARY KEY (
	"PAPER_NO"
);

ALTER TABLE "TEACHER_PROFILE" ADD CONSTRAINT "PK_TEACHER_PROFILE" PRIMARY KEY (
	"TEACHER_NO"
);

ALTER TABLE "TEACHING_AREA" ADD CONSTRAINT "PK_TEACHING_AREA" PRIMARY KEY (
	"AREA_NO"
);

ALTER TABLE "STUDENT_PROFILE" ADD CONSTRAINT "PK_STUDENT_PROFILE" PRIMARY KEY (
	"STUDENT_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO",
	"BOARD_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"QUESTION_NO"
);

ALTER TABLE "ANSWER" ADD CONSTRAINT "PK_ANSWER" PRIMARY KEY (
	"ANSWER_NO",
	"QUESTION_NO"
);

ALTER TABLE "STUDENT_FAMILY" ADD CONSTRAINT "PK_STUDENT_FAMILY" PRIMARY KEY (
	"FAMILY_NO"
);

ALTER TABLE "COUNSELING" ADD CONSTRAINT "PK_COUNSELING" PRIMARY KEY (
	"COUNSELING_NO"
);

ALTER TABLE "TEACHER_AREA" ADD CONSTRAINT "PK_TEACHER_AREA" PRIMARY KEY (
	"COLUNM_NO",
	"TEACHER_NO",
	"AREA_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"AUTHORITY_CODE"
);

ALTER TABLE "MEMBER_ROLE" ADD CONSTRAINT "PK_MEMBER_ROLE" PRIMARY KEY (
	"MEMBERAUTHORITY_NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_CODE"
);

ALTER TABLE "BUSINESS_LOG" ADD CONSTRAINT "FK_STUDENT_PROFILE_TO_BUSINESS_LOG_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "STUDENT_PROFILE" (
	"STUDENT_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "ANSWER" ADD CONSTRAINT "FK_TEACHER_PROFILE_TO_ANSWER_1" FOREIGN KEY (
	"TEACHER_NO"
)
REFERENCES "TEACHER_PROFILE" (
	"TEACHER_NO"
);

ALTER TABLE "ANSWER" ADD CONSTRAINT "FK_QUESTION_TO_ANSWER_1" FOREIGN KEY (
	"QUESTION_NO"
)
REFERENCES "QUESTION" (
	"QUESTION_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_STUDENT_PROFILE_TO_QUESTION_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "STUDENT_PROFILE" (
	"STUDENT_NO"
);

ALTER TABLE "TEACHER_AREA" ADD CONSTRAINT "FK_TEACHER_PROFILE_TO_TEACHER_AREA_1" FOREIGN KEY (
	"TEACHER_NO"
)
REFERENCES "TEACHER_PROFILE" (
	"TEACHER_NO"
);
ALTER TABLE "TEACHER_AREA" ADD CONSTRAINT "FK_TEACHING_AREA_TO_TEACHER_AREA_1" FOREIGN KEY (
	"AREA_NO"
)
REFERENCES "TEACHING_AREA" (
	"AREA_NO"
);
ALTER TABLE "STUDENT_FAMILY" ADD CONSTRAINT "FK_STUDENT_PROFILE_TO_STUDENT_FAMILY_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "STUDENT_PROFILE" (
	"STUDENT_NO"
);
ALTER TABLE "COUNSELING" ADD CONSTRAINT "FK_COUNSELING_CATEGORY_TO_COUNSELING_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "COUNSELING_CATEGORY" (
	"CATEGORY_NO"
);
ALTER TABLE "FILES" ADD CONSTRAINT "PK_FILE" PRIMARY KEY (
   "FILE_NO",
   "TEACHER_NO"
);

ALTER TABLE "FILES" ADD CONSTRAINT "FK_TEACHER_PROFILE_TO_FILE_1" FOREIGN KEY (
   "TEACHER_NO"
)
REFERENCES "TEACHER_PROFILE" (
   "TEACHER_NO"
);
------------------------------------------------------------
-- ▶ 데이터 인서트 / DATA INSERT ◀
------------------------------------------------------------
------------------------------------------------------------
-- ▷ 카테고리 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.CATEGORY
SET DEFINE OFF;
Insert into C##EYELEVEL.CATEGORY (CATEGORY_CODE,CATEGORY_NAME) values ('CTG01','지역 정보');
Insert into C##EYELEVEL.CATEGORY (CATEGORY_CODE,CATEGORY_NAME) values ('CTG02','학습 정보');
Insert into C##EYELEVEL.CATEGORY (CATEGORY_CODE,CATEGORY_NAME) values ('CTG03','수업 기술');
------------------------------------------------------------
-- ▷ 교류게시판 게시글 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.BOARD
SET DEFINE OFF;
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (1,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 01','CTG01 게시글 제목 01','CTG01','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (2,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 02','CTG01 게시글 제목 02','CTG01','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (3,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 03','CTG01 게시글 제목 03','CTG01','TC03');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (4,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 04','CTG01 게시글 제목 04','CTG01','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (5,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 05','CTG01 게시글 제목 05','CTG01','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (6,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 06','CTG01 게시글 제목 06','CTG01','TC03');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (7,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 07','CTG01 게시글 제목 07','CTG01','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (8,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 08','CTG01 게시글 제목 08','CTG01','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (9,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 09','CTG01 게시글 제목 09','CTG01','TC03');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (10,to_date('22/12/14','RR/MM/DD'),'CTG01 게시글 내용 10','CTG01 게시글 제목 10','CTG01','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (11,to_date('22/12/14','RR/MM/DD'),'CTG02 게시글 내용 01','CTG02 게시글 제목 01','CTG02','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (12,to_date('22/12/14','RR/MM/DD'),'CTG02 게시글 내용 02','CTG02 게시글 제목 02','CTG02','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (13,to_date('22/12/14','RR/MM/DD'),'CTG02 게시글 내용 03','CTG02 게시글 제목 03','CTG02','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (14,to_date('22/12/14','RR/MM/DD'),'CTG02 게시글 내용 04','CTG02 게시글 제목 04','CTG02','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (15,to_date('22/12/14','RR/MM/DD'),'CTG02 게시글 내용 05','CTG02 게시글 제목 05','CTG02','TC03');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (16,to_date('22/12/20','RR/MM/DD'),'CTG02 게시글 내용 06','CTG02 게시글 제목 06','CTG02','TC06');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (17,to_date('22/12/20','RR/MM/DD'),'CTG02 게시글 내용 07','CTG02 게시글 제목 07','CTG02','TC07');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (18,to_date('22/12/20','RR/MM/DD'),'CTG02 게시글 내용 08','CTG02 게시글 제목 08','CTG02','TC08');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (19,to_date('22/12/20','RR/MM/DD'),'CTG02 게시글 내용 09','CTG02 게시글 제목 09','CTG02','TC09');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (20,to_date('22/12/20','RR/MM/DD'),'CTG02 게시글 내용 10','CTG02 게시글 제목 10','CTG02','TC10');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (21,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 01','CTG03 게시글 제목 01','CTG03','TC01');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (22,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 02','CTG03 게시글 제목 02','CTG03','TC02');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (23,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 03','CTG03 게시글 제목 03','CTG03','TC03');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (24,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 04','CTG03 게시글 제목 04','CTG03','TC04');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (25,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 05','CTG03 게시글 제목 05','CTG03','TC05');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (26,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 06','CTG03 게시글 제목 06','CTG03','TC06');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (27,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 07','CTG03 게시글 제목 07','CTG03','TC07');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (28,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 08','CTG03 게시글 제목 08','CTG03','TC08');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (29,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 09','CTG03 게시글 제목 09','CTG03','TC09');
Insert into C##EYELEVEL.BOARD (BOARD_NO,BOARD_DATE,BOARD_CONTENT,BOARD_NAME,CATEGORY_CODE,TEACHER_NO) values (30,to_date('22/12/20','RR/MM/DD'),'CTG03 게시글 내용 10','CTG03 게시글 제목 10','CTG03','TC10');

------------------------------------------------------------
-- ▷ 교류게시판 댓글 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.REPLY
SET DEFINE OFF;
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (1,1,to_date('22/12/14','RR/MM/DD'),'댓글내용1','TC01');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (2,1,to_date('22/12/14','RR/MM/DD'),'댓글내용2','TC02');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (3,1,to_date('22/12/14','RR/MM/DD'),'댓글내용3','TC03');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (4,2,to_date('22/12/14','RR/MM/DD'),'댓글내용4','TC04');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (5,2,to_date('22/12/14','RR/MM/DD'),'댓글내용5','TC05');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (6,2,to_date('22/12/15','RR/MM/DD'),'댓글내용6','TC06');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (7,3,to_date('22/12/16','RR/MM/DD'),'댓글내용7','TC07');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (8,3,to_date('22/12/17','RR/MM/DD'),'댓글내용8','TC08');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (9,3,to_date('22/12/18','RR/MM/DD'),'댓글내용9','TC09');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (10,4,to_date('22/12/19','RR/MM/DD'),'댓글내용10','TC10');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (11,4,to_date('22/12/19','RR/MM/DD'),'댓글내용11','TC01');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (12,4,to_date('22/12/19','RR/MM/DD'),'댓글내용12','TC02');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (13,5,to_date('22/12/19','RR/MM/DD'),'댓글내용13','TC03');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (14,5,to_date('22/12/19','RR/MM/DD'),'댓글내용14','TC04');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (15,5,to_date('22/12/20','RR/MM/DD'),'댓글내용15','TC05');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (16,6,to_date('22/12/20','RR/MM/DD'),'댓글내용16','TC06');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (17,6,to_date('22/12/20','RR/MM/DD'),'댓글내용17','TC07');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (18,6,to_date('22/12/20','RR/MM/DD'),'댓글내용18','TC08');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (19,7,to_date('22/12/20','RR/MM/DD'),'댓글내용19','TC09');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (20,7,to_date('22/12/20','RR/MM/DD'),'댓글내용20','TC10');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (21,7,to_date('22/12/20','RR/MM/DD'),'댓글내용21','TC01');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (22,8,to_date('22/12/20','RR/MM/DD'),'댓글내용22','TC02');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (23,8,to_date('22/12/20','RR/MM/DD'),'댓글내용23','TC03');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (24,8,to_date('22/12/20','RR/MM/DD'),'댓글내용24','TC04');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (25,9,to_date('22/12/20','RR/MM/DD'),'댓글내용25','TC05');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (26,9,to_date('22/12/20','RR/MM/DD'),'댓글내용26','TC06');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (27,9,to_date('22/12/20','RR/MM/DD'),'댓글내용27','TC07');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (28,10,to_date('22/12/20','RR/MM/DD'),'댓글내용28','TC08');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (29,10,to_date('22/12/20','RR/MM/DD'),'댓글내용29','TC09');
Insert into C##EYELEVEL.REPLY (REPLY_NO,BOARD_NO,REPLY_DATE,REPLY_CONTENT,TEACHER_NO) values (30,10,to_date('22/12/20','RR/MM/DD'),'댓글내용30','TC10');

------------------------------------------------------------
-- ▷ 가입 상담 카테고리 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.COUNSELING_CATEGORY
SET DEFINE OFF;
Insert into C##EYELEVEL.COUNSELING_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (1,'국어');
Insert into C##EYELEVEL.COUNSELING_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (2,'영어');
Insert into C##EYELEVEL.COUNSELING_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (3,'수학');
------------------------------------------------------------
-- ▷ 가입 상담 신청 내역 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.COUNSELING
SET DEFINE OFF;
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (18,'010-1132-4443','과제를 많이 내주셨으면 좋겠음','N',2);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (10,'010-4545-4545','국어랑 수학을 먼저 하고, 영어는 1달 정도 지난 후에 아이의 진척도를 보고 추가할 예정','N',1);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (17,'010-4587-7777','아이가 얼마나 잘 따라오는지 확인하고 싶음, 1주일마다 선생님이 간단히 아이의 상황을 알려주면 좋겠음','N',1);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (12,'010-5445-7878','형제가 있는데, 연이어서 수업하길 바람','N',1);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (2,'010-5545-8887','없음아이가 평소에 집중력이 낮아서, 수업 시간을 짧게 여러 번 하기를 바람','N',1);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (5,'010-5555-4444','배고픕니다','N',1);
Insert into C##EYELEVEL.COUNSELING (COUNSELING_NO,COUNSELING_PHONE,COUNSELING_ST,COUNSELING_COM,CATEGORY_NO) values (20,'010-7898-8878','영어 교육 시 특히 발음에 신경 써서 가르쳐주길 바람','N',1);
------------------------------------------------------------
-- ▷ 학습지 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.PAPER_INFOMATION
SET DEFINE OFF;
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (1,'자음 모음 읽기','A1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (2,'동요, 그림 카드를 통한 단어 읽기','A2','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (3,'그림책을 통한 문장 읽기','A3','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (4,'자음 모음 쓰기, 단어 따라 쓰기','A4','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (5,'문장 따라 쓰기','A5','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (6,'기본문, 여러 가지 표현을 이용한 문장 만들기','B1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (7,'임자말, 풀이말, 꾸며주는 말','C1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (8,'낱말 풀이, 내용 파악하기','D1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (9,'문장의 성분과 모양, 바꾸어 써보기','E1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (10,'물음과 대답하기','F1','국어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (11,'단어 듣기 말하기','A1','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (12,'문장 듣기 말하기','A2','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (13,'단어, 구, 문장 쓰기','A3','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (14,'다양한 인칭 대명사','A4','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (15,'간단한 대화문 읽고 쓰기','A5','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (16,'[기본 문법] be 동사, 일반 동사 현재형','B1','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (17,'[기본 문법] 일반 동사의 과거형, 미래형','B2','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (18,'[기본 문법] 대명사, 조동사, 감탄문, 비교','B3','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (19,'[심화 문법] 동명사, to 부정사, 접속사','C1','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (20,'[심화 문법] 수동태, 현재/과거 완료, 분사 구문','C2','영어');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (21,'숫자 세기, 읽기','A1','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (22,'숫자표 놀이','A2','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (23,'숫자 따라 쓰기','A3','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (24,'100까지의 덧셈','A4','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (25,'두 자리 더하기','A5','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (26,'덧셈과 뺄셈 (작은 수)','B1','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (27,'덧셈과 뺄셈 (큰 수)','B2','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (28,'구구단','B3','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (29,'곱셈과 나눗셈','B4','수학');
Insert into C##EYELEVEL.PAPER_INFOMATION (PAPER_NO,PAPER_NAME,PAPER_DIFF,PAPER_SUB) values (30,'분수와 약분','B5','수학');
------------------------------------------------------------
-- ▷ 학생 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.STUDENT_PROFILE
SET DEFINE OFF;
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (1,'이단이','student01','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-7897-8788','서울 강서구 양천로58 동아아파트201동101호',to_date('19/09/12','RR/MM/DD'),'ADHD','Y',25);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (2,'유도영','student02','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-4556-5987','서울 구로구 경인로661 푸르지오 201동 1801호',to_date('20/11/23','RR/MM/DD'),null,'Y',14);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (3,'전우주','student03','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-1379-7913','서울 금천구 금하로 750',to_date('19/10/29','RR/MM/DD'),null,'Y',3);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (4,'유연지','student04','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-2555-5888','서울 동작구 만양로8길 50 우성 101동 801호',to_date('20/06/21','RR/MM/DD'),null,'N',4);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (5,'하혜경','student05','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-2580-2580','서울 서대문구 홍제동 270-190',to_date('21/08/15','RR/MM/DD'),null,'Y',5);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (6,'정혜지','student06','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-9797-9797','서울 강서구 양천로58 동아아파트201동101호',to_date('22/02/19','RR/MM/DD'),null,'N',7);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (7,'성규현','student07','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-5950-5950','서울 구로구 경인로661 푸르지오 201동 1801호',to_date('21/12/23','RR/MM/DD'),'주의력 결핍','Y',12);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (8,'김성오','student08','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-5545-5959','서울 금천구 금하로 750',to_date('22/04/12','RR/MM/DD'),null,'Y',13);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (9,'전서혜','student09','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-1431-3045','서울 동작구 여의대방로22나길 40',to_date('21/10/03','RR/MM/DD'),null,'N',1);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (10,'박기선','student10','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-1868-5317','서울 마포구 양화로 45 메세나폴리스 2동 2101호',to_date('20/05/19','RR/MM/DD'),'공부 잘함','N',8);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (11,'전범모','student11','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-1367-8746','서울 서대문구 가재울로 45',to_date('21/03/09','RR/MM/DD'),null,'Y',9);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (12,'정병선','student12','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-8212-7042','서울 구로구 고척로49 골든아파트 1101호',to_date('20/12/13','RR/MM/DD'),null,'Y',11);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (13,'안지유','student13','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-8998-7787','서울 성동구 살곶이길50 3층',to_date('19/11/21','RR/MM/DD'),null,'Y',7);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (14,'안남현','student14','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-2722-5580','서울 광진구 동일로52길 27',to_date('22/02/14','RR/MM/DD'),null,'Y',6);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (15,'전미혜','student15','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-8978-7787','서울 구로구 경인로661 푸르지오 201동 1801호',to_date('21/06/29','RR/MM/DD'),null,'Y',4);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (16,'최애순','student16','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-7897-8988','서울 금천구 금하로 750',to_date('19/08/18','RR/MM/DD'),null,'N',3);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (17,'전정만','student17','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-3386-3304','서울 동작구 만양로8길 50 우성 101동 801호',to_date('20/09/11','RR/MM/DD'),null,'Y',20);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (18,'정재환','student18','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-8332-6337','서울 서대문구 홍제동 270-190',to_date('21/05/23','RR/MM/DD'),null,'Y',13);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (19,'김희운','student19','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-7536-0742','서울 강서구 양천로58 동아아파트201동101호',to_date('20/11/10','RR/MM/DD'),null,'Y',16);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (20,'강서원','student20','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-2008-5413','서울 구로구 경인로661 푸르지오 201동 1801호',to_date('22/10/12','RR/MM/DD'),null,'Y',17);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (21,'박희영','student21','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-0728-5371','서울 금천구 금하로 750',to_date('19/09/26','RR/MM/DD'),null,'Y',18);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (22,'갈서현','student22','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-2577-6685','서울 동작구 여의대방로22나길 40',to_date('21/01/21','RR/MM/DD'),null,'Y',20);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (23,'임수혁','student23','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-0307-4050','서울 마포구 양화로 45 메세나폴리스 2동 2101호',to_date('22/10/30','RR/MM/DD'),null,'Y',14);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (24,'안유승','student24','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-6305-3854','서울 서대문구 가재울로 45',to_date('21/04/13','RR/MM/DD'),null,'Y',13);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (25,'조유윤','student25','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','여','010-2018-0413','서울 구로구 고척로49 골든아파트 1101호',to_date('19/11/23','RR/MM/DD'),null,'Y',17);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (26,'김기택','student26','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-7243-8645','서울 성동구 살곶이길50 3층',to_date('20/08/22','RR/MM/DD'),null,'Y',4);
Insert into C##EYELEVEL.STUDENT_PROFILE (STUDENT_NO,STUDENT_NAME,STUDENT_ID,STUDENT_PW,STUDENT_GENDER,STUDENT_PHONE,STUDENT_ADDRESS,STUDENT_REGIST,STUDENT_MEMO,STUDENT_STATUS,AREA_NO) values (27,'승재문','student27','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','남','010-2027-4824','서울 광진구 동일로52길 27',to_date('21/05/19','RR/MM/DD'),null,'Y',5);

------------------------------------------------------------
-- ▷ 학생 가족 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.STUDENT_FAMILY
SET DEFINE OFF;
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (1,'부','010-8788-7777',35,1);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (103,'모','010-7898-7877',42,1);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (2,'모','010-5777-5777',34,2);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (3,'부','010-5555-7997',44,3);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (4,'모','010-1591-1591',43,4);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (5,'부','010-1588-1588',38,5);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (6,'모','010-6464-6464',36,6);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (7,'부','010-4444-5555',41,7);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (8,'모','010-6464-6464',40,8);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (9,'부','010-1133-1133',36,9);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (10,'모','010-5511-5511',28,10);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (11,'부','010-2077-8360',31,11);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (12,'모','010-3022-5782',34,12);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (101,'모','010-5454-7878',42,13);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (14,'부','010-7877-8888',39,14);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (15,'모','010-8987-2233',34,15);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (16,'부','010-8978-7787',42,16);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (17,'모','010-0474-4244',33,17);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (18,'부','010-3631-2073',39,18);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (19,'부','010-8644-1254',38,19);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (20,'부','010-3234-8053',45,20);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (21,'모','010-1431-3045',41,21);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (22,'모','010-1868-5317',29,22);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (23,'부','010-1367-8746',31,23);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (24,'모','010-8212-7042',36,24);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (25,'모','010-0807-6507',38,25);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (155,'부','010-5545-4554',24,25);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (26,'부','010-2722-5580',34,26);
Insert into C##EYELEVEL.STUDENT_FAMILY (FAMILY_NO,FAMILY_REL,FAMILY_PHONE,FAMILY_AGE,STUDENT_NO) values (27,'부','010-0535-3643',44,27);

------------------------------------------------------------
-- ▷ 교습 지역 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.TEACHING_AREA
SET DEFINE OFF;
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (1,'서울특별시','종로구','평창동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (2,'서울특별시','종로구','부암동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (3,'서울특별시','종로구','청운효자동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (4,'서울특별시','종로구','삼청동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (5,'서울특별시','종로구','무악동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (6,'서울특별시','종로구','교남동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (7,'서울특별시','종로구','사직동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (8,'서울특별시','종로구','가희동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (9,'서울특별시','종로구','혜화동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (10,'서울특별시','종로구','이화동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (11,'서울특별시','종로구','종로1가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (12,'서울특별시','종로구','종로2가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (13,'서울특별시','종로구','종로3가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (14,'서울특별시','종로구','종로4가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (15,'서울특별시','종로구','종로5가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (16,'서울특별시','종로구','종로6가동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (17,'서울특별시','종로구','창신1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (18,'서울특별시','종로구','창신2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (19,'서울특별시','종로구','창신3동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (20,'서울특별시','종로구','숭인1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (21,'서울특별시','종로구','숭인2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (22,'서울특별시','중구','고동동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (23,'서울특별시','중구','회현동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (24,'서울특별시','중구','명동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (25,'서울특별시','중구','필동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (26,'서울특별시','중구','장충동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (27,'서울특별시','중구','광희동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (28,'서울특별시','중구','을지로동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (29,'서울특별시','중구','신당동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (30,'서울특별시','중구','다산동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (31,'서울특별시','중구','약수동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (32,'서울특별시','중구','청구동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (33,'서울특별시','중구','신당5동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (34,'서울특별시','중구','동화동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (35,'서울특별시','중구','황학동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (36,'서울특별시','중구','중림동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (37,'서울특별시','성북구','성북동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (38,'서울특별시','성북구','삼선동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (39,'서울특별시','성북구','동선동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (40,'서울특별시','성북구','돈암1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (41,'서울특별시','성북구','돈암2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (42,'서울특별시','성북구','안암동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (43,'서울특별시','성북구','보문동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (44,'서울특별시','성북구','정릉1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (45,'서울특별시','성북구','정릉2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (46,'서울특별시','성북구','정릉4동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (47,'서울특별시','성북구','길음1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (48,'서울특별시','성북구','길음2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (49,'서울특별시','성북구','종암동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (50,'서울특별시','성북구','월곡1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (51,'서울특별시','성북구','월곡2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (52,'서울특별시','성북구','장위1동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (53,'서울특별시','성북구','장위2동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (54,'서울특별시','성북구','장위3동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (55,'서울특별시','성북구','석관동');
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (56,'서울특별시','용산구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (57,'서울특별시','성동구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (58,'서울특별시','광진구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (59,'서울특별시','동대문구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (60,'서울특별시','중랑구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (61,'서울특별시','강북구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (62,'서울특별시','도봉구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (63,'서울특별시','노원구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (64,'서울특별시','은평구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (65,'서울특별시','서대문구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (66,'서울특별시','마포구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (67,'서울특별시','양천구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (68,'서울특별시','강서구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (69,'서울특별시','구로구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (70,'서울특별시','금천구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (71,'서울특별시','영등포구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (72,'서울특별시','동작구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (73,'서울특별시','관악구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (74,'서울특별시','서초구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (75,'서울특별시','강남구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (76,'서울특별시','송파구',null);
Insert into C##EYELEVEL.TEACHING_AREA (AREA_NO,AREA_SI,AREA_GU,AREA_DONG) values (77,'서울특별시','강동구',null);
------------------------------------------------------------
-- ▷ 교사 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.TEACHER_PROFILE
SET DEFINE OFF;
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC01','고은영',null,'서울 강남구','010-7777-7111','coco@iopk.com','teacher01','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','여러분의 성적을 책임지는! 수학 전문 교사입니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC02','구도연',null,'서울 송파구','010-4124-2315','mindodol@iopk.com','teacher02','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','차곡차곡 한계단씩 학생들의 성적을 올려드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC03','김석훈',null,'서울 양천구','010-1221-2112','shkim1822@iopk.com','teacher03','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','재미있게 가르치고 흥미를 갖게 하는 영어 전문 교사입니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC04','김장선',null,'서울 금천구','010-1919-1919','jskim@iopk.com','teacher04','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','석사졸','심리학과 졸업하여 학생들의 마음도 챙기는 선생님입니다');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC05','남혜정',null,'서울 관악구','010-1234-4321','namhj22@iopk.com','teacher05','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','정직하고 성실함이 제 모토입니다 바른 인성으로 가르치겠습니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC06','노경환',null,'서울 성북구','010-7239-3769','noyang816@iopk.com','teacher06','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','학업에 열의를 보이는 학생들에게 스파르타로 가르칩니다');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC07','문병욱',null,'서울 서초구','010-9999-8888','bumkk1@iopk.com','teacher07','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','박사졸','음악과 놀이를 통해 학생들에게 더욱 흥미를 갖게끔 유도하며 가르칩니다');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC08','문현승',null,'서울 종로구','010-2252-2513','moongus@iopk.com','teacher08','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','국어전공으로 학생들의 언어능력은 책임지고 향상시켜 드리겠습니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC09','박민선',null,'서울 동작구','010-2381-2831','mslove44@iopk.com','teacher09','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','영어권에서 나고 자라 네이티브한 영어 실력으로 가르쳐드립니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC10','백민서',null,'서울 성북구','010-6564-9234','100minseo@iopk.com','teacher10','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','내 사전에 수포자란 없다! 기초부터 차근차근 수학에 흥미를 갖도록 가르치는 선생님입니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC11','설민서',null,'서울 도봉구','010-2332-2112','tjfalstj@iopk.com','teacher11','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','기초부터 탄탄히 쌓을수 있도록 도와드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC12','설성한',null,'서울 중랑구','010-9595-4343','snowsung@iopk.com','teacher12','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','놀이처럼 재미있게 우리아이 맞춤교육!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC13','송가영',null,'서울 노원구','010-9998-9065','songgy1241@iopk.com','teacher13','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','반복학습 으로 아이가 다 흡수할수 있도록 도와드립니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC14','송혜림',null,'서울 성북구','010-5252-6363','songhl@iopk.com','teacher14','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','학습력 쑥쑥! 우리아이 의지도 쑥쑥!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC15','양은채',null,'서울 관악구','010-9966-4456','sheepec@iopk.com','teacher15','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','아이들이 더 재미있고 편하게 공부할수 있도록 도와드립니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC16','윤요한',null,'서울 종로구','010-9656-4554','yoonhan@iopk.com','teacher16','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','석사졸','사교육비 걱정 없는 세상! 함께 만들어 드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC17','이샛별',null,'서울 양천구','010-1419-2423','2totquf@iopk.com','teacher17','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','기초탄탄! 앞으로 성적도 탄탄대로! 도와드립니다');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC18','이인홍',null,'서울 강서구','010-8913-5970','lih22kr@iopk.com','teacher18','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','아이들의 눈높이에 맞게 더 재미있고 어렵지 않게 교육하겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC19','이현승',null,'서울 광진구','010-1231-1424','hslee@iopk.com','teacher19','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','무엇이든 기초가 가장 중요합니다 열심히 가르치겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC20','임환웅',null,'서울 강북구','010-9760-6085','dlaaksdnd1@iopk.com','teacher20','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','우리아이 첫 교육은 제가 책임지고 도와드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC21','장유리',null,'서울 구로구','010-5555-5555','yuri91@iopk.com','teacher21','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','석사졸','선행학습을 통해 앞서 나아가는 아이를 만들어드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC22','전동건',null,'서울 동대문구','010-5657-5675','dongg@iopk.com','teacher22','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','유아교육과 출신으로 아이들을 더 잘 대할수 있습니다! 믿어주세요!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC23','정영신',null,'서울 양천구','010-5235-2341','jung0sin@iopk.com','teacher23','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','집중밀착케어 학습지 하나면 충분합니다! ');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC24','정혜진',null,'서울 영등포구','010-1111-1111','hj1277@iopk.com','teacher24','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','방학에 집중케어로 성적 쑥쑥! 알차게 알려드립니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC25','조무열',null,'서울 중구','010-5564-3535','jomu10@iopk.com','teacher25','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','"수학이 정말 재미있어요!" 아이가 먼저 공부를 찾도록 도와드리겠습니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC26','조한길',null,'서울 은평구','010-3453-3532','jooneload@iopk.com','teacher26','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','공부 습관을 잡는 최적의 시기입니다! 꾸준한 연습으로 공부 습관을 잡아드리겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC27','주규민',null,'서울 강동구','010-1414-1423','ping9@iopk.com','teacher27','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','하브루타,슬로리딩 등 여러 노하우를 이용해 아이가 확실하게 흡수할수 있도록 도와드립니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC28','최나영',null,'서울 강북구','010-1412-6954','skdudchoi@iopk.com','teacher28','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','대졸','중학생이 되기 전 걱정없도록 기초를 제대로 잡아드리겠습니다.');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC29','홍유리',null,'서울 용산구','010-2523-2596','hglass@iopk.com','teacher29','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','석사졸','어릴때 부터 반복학습을 통해 우리아이에게 꿈의 선택지를 늘려줄수 있도록 가르치겠습니다!');
Insert into C##EYELEVEL.TEACHER_PROFILE (TEACHER_NO,TEACHER_NAME,TEACHER_PICTURE,TEACHER_ADDRESS,TEACHER_PHONE,TEACHER_EMAIL,TEACHER_ID,TEACHER_PW,TEACHER_ENT,TEACHER_LEVEL,TEACHER_PR) values ('TC30','홍이슬',null,'서울 마포구','010-2141-1412','hong2@iopk.com','teacher30','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','N','초대졸','수학.국어.영어에 집중하여 아이의 학습 능력에 대한 자존감을 높여드리겠습니다!');
------------------------------------------------------------
-- ▷ 교사 교습 지역 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.TEACHER_AREA
SET DEFINE OFF;
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (1,'TC01',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (2,'TC01',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (3,'TC02',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (4,'TC02',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (5,'TC03',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (6,'TC03',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (7,'TC04',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (8,'TC04',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (9,'TC05',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (10,'TC05',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (11,'TC06',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (12,'TC06',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (13,'TC07',11);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (14,'TC07',12);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (15,'TC08',13);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (16,'TC08',14);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (17,'TC09',15);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (18,'TC09',16);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (19,'TC10',17);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (20,'TC10',18);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (21,'TC11',19);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (22,'TC11',20);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (23,'TC12',20);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (24,'TC12',21);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (25,'TC13',24);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (26,'TC13',25);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (27,'TC14',24);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (28,'TC14',25);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (29,'TC15',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (30,'TC15',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (31,'TC16',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (32,'TC16',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (33,'TC17',1);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (34,'TC17',2);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (35,'TC18',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (36,'TC18',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (37,'TC19',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (38,'TC19',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (39,'TC20',6);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (40,'TC20',7);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (41,'TC21',11);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (42,'TC21',12);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (43,'TC22',13);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (44,'TC22',14);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (45,'TC23',15);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (46,'TC23',16);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (47,'TC24',17);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (48,'TC24',18);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (49,'TC25',19);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (50,'TC25',20);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (51,'TC26',20);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (52,'TC26',21);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (53,'TC27',24);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (54,'TC27',25);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (55,'TC28',24);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (56,'TC28',25);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (57,'TC29',52);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (58,'TC29',53);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (59,'TC30',52);
Insert into C##EYELEVEL.TEACHER_AREA (COLUNM_NO,TEACHER_NO,AREA_NO) values (60,'TC30',54);
------------------------------------------------------------
-- ▷ 질문 게시판 ◁
------------------------------------------------------------

------------------------------------------------------------
-- ▷ 질문 게시판 댓글 ◁
------------------------------------------------------------

------------------------------------------------------------
-- ▷ 관리자 정보 ◁
------------------------------------------------------------
REM INSERTING into C##EYELEVEL.ADMIN
SET DEFINE OFF;
Insert into C##EYELEVEL.ADMIN (ADMIN_CODE,ADMIN_ID,ADMIN_PW,ADMIN_NAME) values (1,'admin','$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK','관리자');
------------------------------------------------------------
-- ▷ 계정별 권한 ◁
------------------------------------------------------------
-- REM INSERTING into C##EYELEVEL.AUTHORITY
-- SET DEFINE OFF;
-- Insert into C##EYELEVEL.AUTHORITY (AUTHORITY_CODE,AUTHORITY_NAME) values (1,'ROLE_ADMIN');
-- Insert into C##EYELEVEL.AUTHORITY (AUTHORITY_CODE,AUTHORITY_NAME) values (2,'ROLE_TEACHER');
-- Insert into C##EYELEVEL.AUTHORITY (AUTHORITY_CODE,AUTHORITY_NAME) values (3,'ROLE_STUDENT');

